# Generated by Django 3.2.23 on 2023-11-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ghbccb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cxvxb', models.BigIntegerField()),
                ('reyeui', models.FloatField()),
            ],
        ),
    ]
